### ISSUE TITLE
Remove Expect header when Post'ing

### ISSUE THREAD

**Issue by tomjebo** [OfficeDev/Interop-TestSuites#16]
Discussing with the dev team here, for the MAPIHTTP tests, the header 'Expect: 100-continue' is added by HttpWebRequest class of .Net when sending a POST request.  This is not needed and has no effect on the tests (at least for MAPIHTTP). 

We should change the ServicePointManager.Expect100Continue property to false to turn off this header. This will allow the traffic to match more closely with Outlook and possibly other clients.

**Comment by XinwLi** [comment]
This issue has be fixed on MS-MAPIHTTP test suite.
