### ISSUE TITLE
FssWopiTestSuiteDeploymentGuide.docx refers to Microsoft Connect

### ISSUE THREAD

**Issue by tomjebo** [OfficeDev/Interop-TestSuites#20]
in chapter 3, it says:
3	Deploying the test suites
This section describes the deployment of the SharePoint File Sync and WOPI Protocol test suites on the test suite client and the SUT. **The SharePoint Server Protocol test suites are packaged in a .zip file which is available on _Microsoft Connect_.** Once you download the test suites, you need to perform the following steps in order to be able to successfully configure the test suites.

If you follow the hyperlink for "Microsoft Connect" it takes you to the redirect site: 
https://docs.microsoft.com/en-us/collaborate/connect-redirect

Can we update these documents to point to the github repo instead?

**Comment by XinwLi** [comment]
This issue has be fixed in FssWopiTestSuiteDeploymentGuide.docx
