### ISSUE TITLE
MSOXCMSG_S01_TC04_RopSaveChangesMessageWithInvalidSaveFlags misleading use of NotSupportedSaveFlags

### ISSUE THREAD

**Issue by tomjebo** [OfficeDev/Interop-TestSuites#31]
MSOXCMSG_S01_TC04_RopSaveChangesMessageWithInvalidSaveFlags(): 

            RopSaveChangesMessageRequest saveChangesMessageRequest = new RopSaveChangesMessageRequest()
            {
                RopId = (byte)RopId.RopSaveChangesMessage,
                LogonId = CommonLogonId,
                InputHandleIndex = CommonInputHandleIndex,
                ResponseHandleIndex = CommonOutputHandleIndex, // This index specifies the location in the Server object handle table that is referenced in the response.
                **SaveFlags = NotSupportedSaveFlags**
            };
            this.ResponseSOHs = this.MSOXCMSGAdapter.DoRopCall(saveChangesMessageRequest, targetMessageHandle, ref this.response, ref this.rawData, GetPropertiesFlags.None);
            RopSaveChangesMessageResponse saveChangesMessageResponse = (RopSaveChangesMessageResponse)this.response;

            // Add the debug information
            Site.Log.Add(LogEntryKind.Debug, "Verify MS-OXCMSG_R1052");

            // Verify MS-OXCMSG requirement: MS-OXCMSG_R1052
            Site.CaptureRequirementIfAreEqual<uint>(
                **0x80040102,**
                saveChangesMessageResponse.ReturnValue,
                1052,
                @"[In Receiving a RopSaveChangesMessage ROP Request] [ecNotSupported (0x80040102)] The values of the SaveFlags are not a supported combination.");
            #endregion

This uses NotSupportedSaveFlags which is 0x0F. Expecting 0x80040102 or not supported error. The problem is that this is misleading to implementers in that 0x0F implies that 0x08 (not defined in the [MS-OXCMSG] 2.2.3.3.1 table of three flags (0x01, 0x02 and 0x04)) is the problem here. 0x08 is not defined in the specification but should be ignored and not cause an error.

The real reason for the 0x80040102 response is that 0x01 and 0x02 are mutually exclusive. This will be an error for Exchange server and should be caught by implementers. 0x08 should be allowed but ignored.

Better to change the test flags passed to RopSaveChangesMessage to 0x03 to clarify what the problem is.

**Comment by XinwLi** [comment]
Fix this issue: update the value of NotSupportedSaveFlags to 0x03.
