### ISSUE TITLE
Bad description in MSOXCFOLD_S01_TC03_RopCreateFolderSuccess

### ISSUE THREAD

**Issue by st-gwerner** [OfficeDev/Interop-TestSuites#32]
In the last few lines of MSOXCFOLD_S01_TC03_RopCreateFolderSuccess, it validates that pidTagMessageSizeExtended == 0.  The description that asserts on failure is:

[In PidTagContentCount Property] The PidTagContentCount property ([MS-OXPROPS] section 2.642) specifies the number of messages in a folder, as computed by the message store.

Since the CaptureRequirementIfAreEqual call doesn't actually refer to PidTagContentCount, either the description or the assertion should be fixed.

**Comment by XinwLi** [comment]
Fix this issue.

**Comment by tomjebo** [comment]
@st-gwerner thanks for helping us improve the test suites! @XinwLi Thanks for fixing these so promptly!
