### ISSUE TITLE
MSOXCFXICS_S03_SyncFastTransferAttachmentLevel_TestSuite validating incorrect handle object

### ISSUE THREAD

**Issue by lduran-smartertools** [OfficeDev/Interop-TestSuites#34]
I was running unit test MSOXCFXICS_S03_SyncFastTransferAttachmentLevel_TestSuite and I think it's setting the display name property on the wrong server handle object.  On line 136 it's calling SetProperties on index 3 which is the message object and not the attachment object which is index 4.  I know you can set a display name on message and attachments but since the test is referencing attachments it feels like that's where the property should be set.

If it's not a bug and the message object's display name is the intended server handle then we can close this issue.  However, if it should be set on the attachment then changing the index to 4 should resolve the issue.

**Comment by XinwLi** [comment]
Fix this issue and close it.
