### ISSUE TITLE
Validating a OneNote .one file from OnPrem OneNote

### ISSUE THREAD

**Issue by nddipiazza** [OfficeDev/Interop-TestSuites#67]
After a recent PR was merged, I have now successfully used this test suite to validate One Note files that have been saved from Office 365 / SharePoint Online. 

```
      byte[] oneNoteBytes = File.ReadAllBytes(@"C:\test\saved-from-sharepoint-online.one");

      SharedContext.Current.IsMsFsshttpRequirementsCaptured = false;
      AlternativePackaging alternatePackageOneStoreFile = new AlternativePackaging();
      alternatePackageOneStoreFile.DoDeserializeFromByteArray(oneNoteBytes, 0);

      MSONESTOREParser onenoteParser = new MSONESTOREParser();
      MSOneStorePackage package = onenoteParser.Parse(alternatePackageOneStoreFile.dataElementPackage);
```

So far so good! Thanks to @xian-rong for all the work on that. 

Would it be easy to modify this test suite such that there is a way to use the test suite to parse a file that was saved from Microsoft Office on prem?

**Comment by ChangDu2021** [comment]
@nddipiazza about Microsoft Office on prem, do you means that you want to parse a .one file saved from local OneNote app directly?

**Comment by ChangDu2021** [comment]
@nddipiazza 
You want to use following code to read .one file from local OneNote app, right?
byte[] oneNoteBytes = File.ReadAllBytes(@"C:\test\saved-from-local-onenote-app.one");

**Comment by nddipiazza** [comment]
> @nddipiazza about Microsoft Office on prem, do you means that you want to parse a .one file saved from local OneNote app > directly?
correct
> @nddipiazza
> You want to use following code to read .one file from local OneNote app, right?
> byte[] oneNoteBytes = File.ReadAllBytes(@"C:\test\saved-from-local-onenote-app.one");
That's right.

**Comment by tomjebo** [comment]
Hey @nddipiazza, 

the .one file format saved by the OneNote desktop apps and described in MS-ONE does not contain the transfer encoding (i.e. FSSHTTP components) that is used when transferring from Sharepoint. Therefore this test suite does not have that functionality right now and likely won't add code to test the file format outside of transfer format. This request should be considered a feature or enhancement request. I'll let @ChangDu2021 give the final response on whether the engineering team can add this new feature.

Thanks,
Tom

**Comment by nddipiazza** [comment]
my needs were fixed by this https://github.com/OfficeDev/Interop-TestSuites/pull/65

i just neglected to close this.

**Comment by ChangDu2021** [comment]
@nddipiazza Could you please try below code snippet to parse a local .one file? Its structure is different from ones described in 2.7 and 2.8. It is described in 3.1 about structure example. I also attached the test file, it works at my side. 

using System;
using Microsoft.Protocols.TestSuites.MS_ONESTORE;
using System.IO;

namespace ConsoleApp1
{
class Program
{
static void Main(string[] args)
{
string fileUrl = @"C:\v-xianrong\interop\Interop-TestSuites\FileSyncandWOPI\Source\MS-ONESTORE\ConsoleApp1\Section1.one";
byte[] buffer = File.ReadAllBytes(fileUrl);
OneNoteRevisionStoreFile oneNoteFile = new OneNoteRevisionStoreFile();
oneNoteFile.DoDeserializeFromByteArray(buffer);
}
}
}
[TestParseLocalOneNote.zip](https://github.com/OfficeDev/Interop-TestSuites/files/8230781/TestParseLocalOneNote.zip)
