### ISSUE TITLE
There was a problem with the order in which the response buffers were parsed！

### ISSUE THREAD

**Issue by lmou523** [OfficeDev/Interop-TestSuites#74]
Clearly stated in the official documentation: https://docs.microsoft.com/en-us/openspecs/exchange_server_protocols/ms-oxcrpc/4c01d3be-2f25-458a-8ed2-14cb110f9cec
For buffers: they should be de-obfuscated before being decompressed.
But in this project, much of the processing is reversed.

**Comment by ChangDu2021** [comment]
@lmou523 I am from Test Suite dev team. I am working on your issue. Could you please provide more detail info if you could? eg code snippet and .saz session saved from Fiddler.

**Comment by lmou523** [comment]
![image](https://user-images.githubusercontent.com/59944420/173721430-8f13b3ac-df7b-4c82-9fcd-dc8fb7399877.png)
here

**Comment by ChangDu2021** [comment]
@lmou523 Yes, you are right. Could you please exchange the order for these two IF statements at your side at first? And do you still get any issues after done? I will update the code. And could you please let me know if XorMagic flag exists in your buffers and what is your request to exchange server?

**Comment by lmou523** [comment]
I don't have a problem. I just happened to see it here.

**Comment by ChangDu2021** [comment]
@lmou523 Thanks for your update.
