### ISSUE TITLE
There is a problem with the LZ77Decompress function

### ISSUE THREAD

**Issue by lmou523** [OfficeDev/Interop-TestSuites#75]
![image](https://user-images.githubusercontent.com/59944420/173722574-2a3562d6-45be-49b0-9581-25bc39c56bea.png)
When calculating the length, you don't take into account the existence of a shared byte.

This will cause the length of your calculation to be wrong, resulting in overstepping/decompression failure

**Comment by ChangDu2021** [comment]
@lmou523, for this code snippet, it is used to get the length that are equal to 280 or greater. Based on the document, the length is calculated ONLY from these last 2 bytes, so don't need to add shared bytes. 

![image](https://user-images.githubusercontent.com/81283391/176850969-03d85eb7-d731-4374-b820-d52b7edd3fa5.png)

And here is an example.
![image](https://user-images.githubusercontent.com/81283391/176851232-733f4d3a-309a-44bc-9c6d-7fda557161a8.png)

Please let me know if you have any concerns.

**Comment by lmou523** [comment]
Its error is not in calculating the size

It's where it takes the data

/ / assume that this is a memory: 0x12, 0x23, 0x34, 0x45, 0x67, 0xFF

If the current segment has shared bytes then these two bytes should be 0x67, 0xFF

If the shared bytes from the previous segment are used then these two bytes should be 0x45,0x67

Its code will fetch 0x67 0xFF each time,  will cause the out-of-bounds decompression to fail

**Comment by ChangDu2021** [comment]
@lmou523 Got it. I agree. It depends on if current metadata has shared bytes. For now, it defines a const value. I will work on it.

// The size of final two bytes which is used to calculate the match length equal or greater than 280.
const int SizeOfFinalTwoBytes = 4;

Did you actually call LZ77Decompress? Could you please share your code snippet with me? Then I can debug and fix the issue quickly.

**Comment by lmou523** [comment]
@ChangDu2021  Increments 3 if there are no shared bytes and 4 if there are shared bytes

**Comment by ChangDu2021** [comment]
@lmou523 The changes are in below pull request in my branch. We are planning to merge it into prod branch after testing. Could you please let me know if you find any issues in it? For now, the function is not called when the test case is running. 
https://github.com/ChangDu2021/Interop-TestSuites/pull/35/files
