### ISSUE TITLE
Invalid and missing compound types

### ISSUE THREAD

**Issue by benerobert** [OfficeDev/Interop-TestSuites#91]
Hi! 

The compoundTypes in BaseType.cs do not fully correspond to the table in MS-FSSHTTPB in section 2.2.1.5.2. The value of 'Response (FsshttpbResponse)' is missing and 'Target Partition Id' should be a non-compound type according to the table.

![image](https://user-images.githubusercontent.com/128474016/229783366-a2947de1-eb1c-4c0e-83e5-fc9df9e9ceb8.png)
![image](https://user-images.githubusercontent.com/128474016/229783601-93ce79a3-e149-44be-a6b8-2079cf6adc43.png)

Therefore, a header is added at the end of TargetPartitionId, but it is not required by the protocol specification, since it is not a compound type.

![image](https://user-images.githubusercontent.com/128474016/229795702-5742a782-8f0e-4a61-9e6f-8d9cd2578b81.png)
![image](https://user-images.githubusercontent.com/128474016/229796762-fb15cc56-914a-4c88-95ba-01e181833b35.png)

Have a nice day!

**Comment by ChangDu2021** [comment]
@benerobert 
After I did investigation, the reason why Target Partition Id End is added in Test Suite code is that Target Partition Id End exists in ms-fsshttpb v20140430, but was removed then. I am trying to remove this field from Test Suite code to see if test case is still working.
![image](https://user-images.githubusercontent.com/81283391/230352182-7042823c-5d6f-4968-9c23-493c692eba59.png)

For response field, I think it would be good to add. Now it is not invoked in test suite code, so has not added it.

**Comment by ChangDu2021** [comment]
@benerobert After verification, test suite code works well after removing Target Partition Id End to change Target Partition Id as a single object. The server could response no matter Target Partition Id is a single or compound object in the request. And response is also added. The changes have been merged into my master branch https://github.com/ChangDu2021/Interop-TestSuites, could you please help check if it is working at your side? If yes, I will merge it into prod master branch.
Below is the pull request to have the changes:
https://github.com/ChangDu2021/Interop-TestSuites/pull/50

**Comment by benerobert** [comment]
@ChangDu2021 With this change, tests now run successfully on my site.

**Comment by ChangDu2021** [comment]
@benerobert Sounds good. Could you please close this issue if you don't have any other questions?
