### ISSUE TITLE
XML error after unpacking the editor table

### ISSUE THREAD

**Issue by benerobert** [OfficeDev/Interop-TestSuites#92]
Hi!

During the unpacking of the editor table data, the actual buffer size returned by stream.Read is not taken into account, and as a result the XML load (doc.LoadXml) returns an error (0x00 hexadecimal value, invalid character).

https://github.com/OfficeDev/Interop-TestSuites/blob/26895d66fdf0bb671f369a48270b40ca2005702f/FileSyncandWOPI/Source/SharedTestSuite/SharedAdapter/Helper/EditorsTableUtils.cs#L79

![image](https://user-images.githubusercontent.com/128474016/231761275-3a8f067c-8231-456d-a3e2-e526552c0ba9.png)

This small modification should eliminate the problem:

![image](https://user-images.githubusercontent.com/128474016/231762699-83c60c88-214a-4961-91b0-745647939a22.png)

**Comment by JimZhao2023** [comment]
@benerobert Thanks for your suggestion to optimize the code. I will update the code to resize the decompressBuffer array.
And during my debugging the code, I didn't get the error when loading XML. But it is true that there are too many 0x00 bytes at the end of decompressBuffer byte array. It is better to remove them. Thanks again.

![image](https://user-images.githubusercontent.com/130362797/234535858-4cc121f3-426b-48f0-af86-693c4e1d3769.png)

![image](https://user-images.githubusercontent.com/130362797/234535815-6350cd3e-5cb2-4aae-9128-0e7f7946db44.png)
